version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=netology_aiohttp
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pwd
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d netology_stocks_products"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  web:
    build: ./
    command: "python3 /usr/src/server.py"
    volumes:
      - ./:/usr/src/
      - ./logs:/var/log
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=netology_aiohttp
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_pwd
    depends_on:
      - db
    restart: unless-stopped