# примеры API-запросов

@userUrl = http://127.0.0.1:8080/user/
@stickerUrl = http://127.0.0.1:8080/sticker/
# user1:user1
@basicToken1 = dXNlcjE6dXNlcjE=
# user2:user2
@basicToken2 = dXNlcjI6dXNlcjI=

###

# создание user
POST {{userUrl}}
Content-Type: application/json
Authorization: Basic {{basicToken1}}

{
  "name": "user3",
  "password": "user3"
}
###

# получение user
GET {{userUrl}}/1
Content-Type: application/json
Authorization: Basic {{basicToken1}}
###

# удаление user
DELETE {{userUrl}}/3
Content-Type: application/json
Authorization: Basic {{basicToken2}}
###

# обновление user
PATCH {{userUrl}}/4
Content-Type: application/json
Authorization: Basic {{basicToken1}}

{
  "name": "user33"
}
###

#=================================================================================================

# создание sticker
POST {{stickerUrl}}
Content-Type: application/json
Authorization: Basic {{basicToken1}}

{
  "title": "title101",
  "description": "description101"
}
###

# получение sticker
GET {{stickerUrl}}/1
Content-Type: application/json
Authorization: Basic dXNlcjM6dXNlcjM=
###

# удаление sticker
DELETE {{stickerUrl}}/1
Content-Type: application/json
Authorization: Basic dXNlcjM6dXNlcjM=
###

# обновление sticker
PATCH {{stickerUrl}}/1
Content-Type: application/json
Authorization: Basic {{basicToken1}}

{
  "title": "title177",
  "description": "description177",
  "owner_id": 23
}
###