FROM python:3.11.4
RUN apt update && apt install -y build-essential gcc clang clang-tools cmake python3-dev cppcheck  \
    valgrind afl gcc-multilib

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6

WORKDIR /usr/src/

COPY ./upscale/requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY ./upscale/run.sh ./run.sh
RUN sed -i 's/\r$//g' run.sh
RUN chmod +x run.sh

COPY ./upscale/app.py ./app.py
COPY ./upscale/celery_app.py ./celery_app.py
COPY ./upscale/upscale.py ./upscale.py

CMD bash run.sh
